### ISSUE TITLE
    from pyLindo import lindo ImportError: DLL load failed while importing lindo: The specified module could not be found.

### ISSUE THREAD

**Issue by AlaiY95** [lindosystems/lindoapi-python#2]
I'm trying to run the lindoapi-python sample test file after successfully building the pylindo wheel:
`Successfully built pyLindo-13.0.1.tar.gz and pyLindo-13.0.1-cp38-cp38-win_amd64.whl`

However when i try running the test script within the python directory, i get the following:
```
c:\Lindoapi\python>python samples/lp.py
Traceback (most recent call last):
  File "samples/lp.py", line 17, in <module>
    from pyLindo import *
  File "C:\Users\alaiy\AppData\Local\Programs\Python\Python38\lib\site-packages\pyLindo\__init__.py", line 3, in <module>
    from pyLindo import lindo
ImportError: DLL load failed while importing lindo: The specified module could not be found.
```

I think the error is indicating a missing DLL file so I ran the following in visual studios cmd to find the dependencies in the pylindo pyd in question
```
Dump of file C:\Users\alaiy\AppData\Local\Programs\Python\Python38\Lib\site-packages\pyLindo\lindo.cp38-win_amd64.pyd

File Type: DLL

  Image has the following dependencies:

    lindo64_13_0.dll
    python38.dll
    KERNEL32.dll
    VCRUNTIME140.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll

  Summary

        B000 .data
        2000 .pdata
        7000 .rdata
        1000 .reloc
        1000 .rsrc
       1E000 .text

```
I've found the first 2 files in another folder and i'd copied them into C:\Users\alaiy\AppData\Local\Programs\Python\Python38\Lib\site-packages\pyLindo\ However the issue still persists?

Maybe this because a valid license key is required? However there is a license file with keys within the installed C:\Lindoapi\license directory which contains the info:
```
LINDO API Demo 13.00
Max Users: 1
Node Locked: No
Expiration Date: None
Enabled Solvers:  Linear  Nonlinear  Global  Barrier  Mip  Stochastic  Conic  
Usage: Commercial  
Machine Class: All platforms
Serial#: Lindo
Dongle Required: No
License key: 
```

 Any other reason why I could be receiving the error?

From research it was found that running

**Comment by AlaiY95** [comment]
I was following the instructions from the LINDO_API 19 and using the LindoAPI->python created when installing from the website which did not work. Solution.. downloading files from this repo and installing with instructions worked =D

**Comment by JHaasIII92** [comment]
Hello Alai95,

Glad to hear it is working.
If the LindoAPI is installed and the LINDOAPI_HOME environment variable is set, then all that needs to be done is to
 `pip install lindo`.

Best,
James

**Comment by mkatlihan** [comment]
This error could be because the PATH environment variable is corrupt. 

```ImportError: DLL load failed while importing lindo: The specified module could not be found.```

Make sure your PATH variable includes "c:\lindoapi\bin\win64" (assuming your LINDOAPI_HOME is "c:\lindoapi"). If you have installed LINDO API using the installer exe, this configuration is automatically made. Otherwise, you have to add it manually.

In all cases, it is not advised to move selected DLLs to different places (you cannot be sure what their dependecies are).  Simply, updating the PATH variable with the original folder that DLL resides in should be sufficient.
